development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: notification_server_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: notification_server_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  schannel_prefix: notification_server_production